### ISSUE TITLE
Investigate Vinyl files passed from Gulp stream

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/convert-vinyl-to-vfile#1]
2f4d178abb3402cf186cc076c1d79c53d5d24a63

For some reason, when a Gulp stream passes a "Vinyl file"
Vinyl.isVinyl(vinylFile) fails. Add a `newVinyl = new Vinyl(vinylFile);`
to make sure a Vinyl file is a Vinyl file.

In the future, find out why this is and how to avoid this. This "force"
might cause issues down the road.

**Comment by wooorm** [comment]
@dustinspecker This is already in the code now, right?

**Comment by dustinspecker** [comment]
Yes! I haven't investigated this any further. This may not be need anymore.
