### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by wooorm** [dustinspecker/convert-vinyl-to-vfile#47]
Hi! 👋

I just upped Vinyl (and xo, but not mocha because that’s broken apparently) and fixed the docs.
Dustin, could you release 2.0.0? (I’m not sure about your release mechanism).

**Comment by dustinspecker** [comment]
Hey!

I just published `2.0.0`. For this project, I'm just manually publishing it - nothing fancy. I think you should be an owner on npm for future releases, but please let me know if that's not setup correctly. I also don't mind publishing.

**Comment by wooorm** [comment]
Alright great, thanks Dustin!
